### PR TITLE
Just removing a little "the" :)

### PR DESCRIPTION
**Pull request by zehzinho**

### CODE REVIEW

**Comment by maccman** [comment]
Great - notice there's a lot of removing whitespace in the commit too. Is it possible to make the changes to 01_syntax.md rather than the html file, and use rake to generate the site? Thanks so much.

**Comment by zehzinho** [comment]
Hi, I'm having problems to run rake. I'm using ruby 1.9.2, i18n 0.6.0 and active_support 3.0.0. I know it's such a small issue for the project, but I'm a ruby newbie and would really appreciate any help to make it run. The rake output:

$ rake --trace
(in /home/myuser/arcturo_library/coffeescript)
rake aborted!
undefined method `run_load_hooks' for ActiveSupport:Module
/home/myuser/.rvm/gems/ruby-1.9.2-p180@text/gems/activesupport-3.0.0/lib/active_support/i18n.rb:9:in`<top (required)>'
/home/myuser/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/home/myuser/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
/home/myuser/.rvm/gems/ruby-1.9.2-p180@text/gems/activesupport-3.0.0/lib/active_support/core_ext/string/interpolation.rb:1:in `<top (required)>'
/home/myuser/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
/home/myuser/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/home/myuser/.rvm/gems/ruby-1.9.2-p180@text/gems/activesupport-3.0.0/lib/active_support/core_ext/string.rb:9:in`<top (required)>'
/home/myuser/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:58:in `require'
/home/myuser/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:58:in`rescue in require'
/home/myuser/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
/home/myuser/Sources/text/arcturo_library/coffeescript/Rakefile:3:in`<top (required)>'
/home/myuser/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:2383:in `load'
/home/myuser/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:2383:in`raw_load_rakefile'
/home/myuser/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:2017:in `block in load_rakefile'
/home/myuser/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/home/myuser/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:2016:in `load_rakefile'
/home/myuser/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:2000:in`block in run'
/home/myuser/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/home/myuser/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/lib/rake.rb:1998:in`run'
/home/myuser/.rvm/gems/ruby-1.9.2-p180@global/gems/rake-0.8.7/bin/rake:31:in `<top (required)>'
/home/myuser/.rvm/gems/ruby-1.9.2-p180@global/bin/rake:19:in`load'
/home/myuser/.rvm/gems/ruby-1.9.2-p180@global/bin/rake:19:in `<main>'

Best regards,

Zé

**Comment by maccman** [comment]
a gem update should solve this - ActiveSupport doesn't support the older rake versions.

**Comment by zehzinho** [comment]
Man, thanks a lot. I learned some more ruby and git just to remove this little "the".

Now I guess I can go back and read the rest of the book :P

**Comment by maccman** [comment]
Great, thanks!

**Pull request merged**
